### PR TITLE
Adding support for jupyterlab statusbar-extension #36

### PR DESCRIPTION
**Pull request by Gsbreddy**
This solves yuvipanda#36

Have to raise PR on jupyterlab statusbar-extension to change api call to /api/nbresuse/v1 once this PR is merged.

Once this is done, then we can merge yuvipanda#41 and release a new version to PyPi.

- [x] Add back `psutil` as a dependency
- [x] Add back the `/metrics` endpoint with mem and cpu usage

### CODE REVIEW

**Comment by jtpio** [comment]
How about something like the following timeline?

- Re-release `nbresuse` master as `0.4.0` (with the Prometheus API)
- Yank `0.3.4` on PyPI since it's a breaking change from `0.3.3`
- Merge this PR (https://github.com/yuvipanda/nbresuse/pull/45) to bring back the original JSON response 
- Release `0.5.0` since it adds a new endpoint
- Update core lab to use `/api/nbresuse/v1` 
- https://github.com/yuvipanda/nbresuse/pull/41 could be merged somewhere between since it affects the Prometheus metrics 

Users with JupyterLab <= 2.x will need `nbresuse=0.3.3`
Users with JupyterLab >= 3.x (or the version including the new endpoint) will need `nbresuse==0.5+`

The main issue is to be able to deal with all the breaking changes and what is currently implemented in core JupyterLab.

cc @krinsman if you have any input on this

**Comment by Gsbreddy** [comment]
LGTM.

**Comment by jtpio** [comment]
@Gsbreddy I'm pushing a couple of fixes to:

- add `psutil` back as a dependency
- add the `/metrics` endpoint back (at least for now - discussed in #36) 

Also CI doesn't seem to be triggered, fixing that separately.

**Comment by Gsbreddy** [comment]
Yeah. This would add backward compatibility. But won't this override the prometheus metrics at `/metrics` as you said here. https://github.com/yuvipanda/nbresuse/issues/36#issuecomment-642877003

**Comment by Gsbreddy** [comment]
What about the `/metrics` endpoint? Won't this be a problem as you told here. https://github.com/yuvipanda/nbresuse/issues/36#issuecomment-642877003

**Comment by jtpio** [comment]
Yes, but since we can't yank 0.3.4 at the moment the only option seems to be adding the endpoint back, and releasing 0.3.5. So it's still compatible with older clients for a little while.

**Comment by jtpio** [comment]
> Once this is done, then we can merge #41 and release a new version to PyPi.

We can probably do that separately, especially if we bring back `/metrics`.

We can also bring back the CPU metrics to the API endpoint since it was available in 0.3.3.

**Comment by jtpio** [comment]
> We can also bring back the CPU metrics to the API endpoint since it was available in 0.3.3.

Will push a commit to handle that.

**Comment by Gsbreddy** [comment]
This won't be useful for core lab though. Just the notebook.

**Comment by jtpio** [comment]
This extension depends on it: https://github.com/jtpio/jupyterlab-system-monitor

Also if it's gone it's another breaking change.

**Comment by Gsbreddy** [comment]
Okay. Is there any plan to merge https://github.com/jtpio/jupyterlab-system-monitor to core lab?

**Comment by jtpio** [comment]
Not really, although this could be considered if more people are using it.

We would first need to decide on the future of nbresuse and the scope it should cover. So that we can build and expose a stable API.

**Comment by jtpio** [comment]
@Gsbreddy let me know if you want to try the latest from this branch locally.

There are no test at the moment but we should eventually add some (#49).

**Comment by jtpio** [comment]
Also what do you think about removing the `/api/nbresuse/v1` endpoint for now?

Since it's a new endpoint, there could be a good opportunity to design the API with what we plan to add next in mind (for example kernel metrics).

**Comment by jtpio** [comment]
Merging, we can iterate in separate PRs.

**Comment by jtpio** [comment]
Thanks again @Gsbreddy for this!

**Comment by Gsbreddy** [comment]
Sure! We can add this endpoint later with the design which has more information like per kernel memory and cpu usages. Looking forward to help on this.

**Comment by jtpio** [comment]
That's great, thanks @Gsbreddy!

(I now have commit rights on the repo, so we can keep some momentum)

**Comment by yuvipanda** [comment]
Hello! I appreciate all the fixes here, @jtpio and @Gsbreddy!!!

I've opened https://github.com/yuvipanda/nbresuse/pull/68 with a 'soft deprecation' pathway for the /metrics endpoint, enabling admins to opt-in to removing /metrics for now. Would love y'all taking a look :)

**Pull request merged**
